// 韩语词库 · TOPIK 1-6 · 含词性
// pos: n=名词  v=动词  adj=形容词  adv=副词  expr=表达
export const POS_NAMES = {
  n:    '명사  名词',
  v:    '동사  动词',
  adj:  '형용사  形容词',
  adv:  '부사  副词',
  expr: '표현  表达',
};

export const VOCABULARY = [
  // ==================== TOPIK 1 ====================
  {id:1,  korean:'사람',    rom:'sa-ram',          pos:'n',   meaning:'人',          example:'저 사람은 누구예요?',             exMeaning:'那个人是谁？',          level:1},
  {id:2,  korean:'물',      rom:'mul',             pos:'n',   meaning:'水',          example:'물 한 잔 주세요.',              exMeaning:'请给我一杯水。',        level:1},
  {id:3,  korean:'밥',      rom:'bap',             pos:'n',   meaning:'米饭/饭',     example:'밥 먹었어요?',                  exMeaning:'你吃饭了吗？',          level:1},
  {id:4,  korean:'집',      rom:'jip',             pos:'n',   meaning:'家/房子',     example:'우리 집은 학교 근처에 있어요.',   exMeaning:'我家在学校附近。',      level:1},
  {id:5,  korean:'학교',    rom:'hak-gyo',         pos:'n',   meaning:'学校',        example:'학교에 가요.',                  exMeaning:'去学校。',              level:1},
  {id:6,  korean:'친구',    rom:'chin-gu',         pos:'n',   meaning:'朋友',        example:'친구랑 같이 영화를 봤어요.',      exMeaning:'和朋友一起看了电影。',  level:1},
  {id:7,  korean:'선생님',  rom:'seon-saeng-nim',  pos:'n',   meaning:'老师',        example:'선생님, 질문 있어요.',           exMeaning:'老师，我有问题。',      level:1},
  {id:8,  korean:'나라',    rom:'na-ra',           pos:'n',   meaning:'国家',        example:'어느 나라 사람이에요?',          exMeaning:'你是哪国人？',          level:1},
  {id:9,  korean:'시간',    rom:'si-gan',          pos:'n',   meaning:'时间',        example:'지금 몇 시예요?',               exMeaning:'现在几点了？',          level:1},
  {id:10, korean:'이름',    rom:'i-reum',          pos:'n',   meaning:'名字',        example:'이름이 뭐예요?',                exMeaning:'你叫什么名字？',        level:1},
  {id:11, korean:'가족',    rom:'ga-jok',          pos:'n',   meaning:'家人/家庭',   example:'가족이 몇 명이에요?',            exMeaning:'你家有几口人？',        level:1},
  {id:12, korean:'음식',    rom:'eum-sik',         pos:'n',   meaning:'食物',        example:'한국 음식을 좋아해요.',          exMeaning:'我喜欢韩国食物。',      level:1},
  {id:13, korean:'날씨',    rom:'nal-ssi',         pos:'n',   meaning:'天气',        example:'오늘 날씨가 좋아요.',            exMeaning:'今天天气很好。',        level:1},
  {id:14, korean:'전화',    rom:'jeon-hwa',        pos:'n',   meaning:'电话',        example:'전화번호가 뭐예요?',             exMeaning:'你的电话号码是多少？',  level:1},
  {id:15, korean:'버스',    rom:'beo-seu',         pos:'n',   meaning:'公共汽车',    example:'버스로 학교에 가요.',            exMeaning:'坐公交车去学校。',      level:1},
  {id:16, korean:'지하철',  rom:'ji-ha-cheol',     pos:'n',   meaning:'地铁',        example:'지하철이 빠르고 편해요.',         exMeaning:'地铁又快又方便。',      level:1},
  {id:17, korean:'병원',    rom:'byeong-won',      pos:'n',   meaning:'医院',        example:'병원에 가야 해요.',              exMeaning:'我得去医院。',          level:1},
  {id:18, korean:'시장',    rom:'si-jang',         pos:'n',   meaning:'市场',        example:'시장에서 과일을 샀어요.',         exMeaning:'在市场买了水果。',      level:1},
  {id:19, korean:'책',      rom:'chaek',           pos:'n',   meaning:'书',          example:'책을 읽어요.',                  exMeaning:'读书。',                level:1},
  {id:20, korean:'돈',      rom:'don',             pos:'n',   meaning:'钱',          example:'돈이 없어요.',                  exMeaning:'没有钱。',              level:1},
  {id:21, korean:'옷',      rom:'ot',              pos:'n',   meaning:'衣服',        example:'새 옷을 샀어요.',               exMeaning:'买了新衣服。',          level:1},
  {id:22, korean:'하늘',    rom:'ha-neul',         pos:'n',   meaning:'天空',        example:'하늘이 파랗네요.',              exMeaning:'天空真蓝啊。',          level:1},
  {id:23, korean:'바다',    rom:'ba-da',           pos:'n',   meaning:'大海',        example:'여름에 바다에 갔어요.',           exMeaning:'夏天去了海边。',        level:1},
  {id:24, korean:'산',      rom:'san',             pos:'n',   meaning:'山',          example:'주말에 산에 올라가요.',           exMeaning:'周末爬山。',            level:1},
  {id:25, korean:'길',      rom:'gil',             pos:'n',   meaning:'路/道路',     example:'이 길로 쭉 가세요.',             exMeaning:'沿着这条路一直走。',    level:1},
  {id:26, korean:'문',      rom:'mun',             pos:'n',   meaning:'门',          example:'문을 열어 주세요.',              exMeaning:'请开门。',              level:1},
  {id:27, korean:'방',      rom:'bang',            pos:'n',   meaning:'房间',        example:'제 방은 작아요.',               exMeaning:'我的房间很小。',        level:1},
  {id:28, korean:'침대',    rom:'chim-dae',        pos:'n',   meaning:'床',          example:'침대에서 자요.',                exMeaning:'在床上睡觉。',          level:1},
  {id:29, korean:'의자',    rom:'ui-ja',           pos:'n',   meaning:'椅子',        example:'의자에 앉으세요.',              exMeaning:'请坐在椅子上。',        level:1},
  {id:30, korean:'책상',    rom:'chaek-sang',      pos:'n',   meaning:'书桌',        example:'책상 위에 책이 있어요.',          exMeaning:'桌子上有书。',          level:1},
  {id:31, korean:'가방',    rom:'ga-bang',         pos:'n',   meaning:'包/书包',     example:'가방을 메고 학교에 가요.',        exMeaning:'背着包去学校。',        level:1},
  {id:32, korean:'신발',    rom:'sin-bal',         pos:'n',   meaning:'鞋',          example:'신발을 벗으세요.',              exMeaning:'请脱鞋。',              level:1},
  {id:33, korean:'꽃',      rom:'kkot',            pos:'n',   meaning:'花',          example:'꽃이 예쁘네요.',               exMeaning:'花真漂亮啊。',          level:1},
  {id:34, korean:'나무',    rom:'na-mu',           pos:'n',   meaning:'树',          example:'공원에 나무가 많아요.',           exMeaning:'公园里树很多。',        level:1},
  {id:35, korean:'개',      rom:'gae',             pos:'n',   meaning:'狗',          example:'개가 귀여워요.',               exMeaning:'狗很可爱。',            level:1},
  {id:36, korean:'고양이',  rom:'go-yang-i',       pos:'n',   meaning:'猫',          example:'고양이를 키워요.',              exMeaning:'我养了一只猫。',        level:1},
  {id:37, korean:'사과',    rom:'sa-gwa',          pos:'n',   meaning:'苹果',        example:'사과를 먹고 싶어요.',            exMeaning:'我想吃苹果。',          level:1},
  {id:38, korean:'커피',    rom:'keo-pi',          pos:'n',   meaning:'咖啡',        example:'커피 한 잔 할래요?',             exMeaning:'要喝一杯咖啡吗？',      level:1},
  {id:39, korean:'우유',    rom:'u-yu',            pos:'n',   meaning:'牛奶',        example:'매일 우유를 마셔요.',            exMeaning:'每天喝牛奶。',          level:1},
  {id:40, korean:'빵',      rom:'ppang',           pos:'n',   meaning:'面包',        example:'아침에 빵을 먹어요.',            exMeaning:'早上吃面包。',          level:1},
  {id:41, korean:'공원',    rom:'gong-won',        pos:'n',   meaning:'公园',        example:'공원에서 산책해요.',            exMeaning:'在公园散步。',          level:1},
  {id:42, korean:'날',      rom:'nal',             pos:'n',   meaning:'日/天',       example:'오늘은 좋은 날이에요.',           exMeaning:'今天是好日子。',        level:1},
  {id:43, korean:'물건',    rom:'mul-geon',        pos:'n',   meaning:'东西/物品',   example:'물건을 잃어버렸어요.',           exMeaning:'我丢失了东西。',        level:1},
  {id:44, korean:'색',      rom:'saek',            pos:'n',   meaning:'颜色',        example:'좋아하는 색이 뭐예요?',          exMeaning:'你喜欢什么颜色？',      level:1},
  {id:45, korean:'음료',    rom:'eum-nyo',         pos:'n',   meaning:'饮料',        example:'음료를 주문했어요.',            exMeaning:'点了饮料。',            level:1},
  {id:46, korean:'아침',    rom:'a-chim',          pos:'n',   meaning:'早上/早饭',   example:'아침을 먹고 출근해요.',           exMeaning:'吃完早饭去上班。',      level:1},
  {id:47, korean:'점심',    rom:'jeom-sim',        pos:'n',   meaning:'午饭',        example:'점심 뭐 먹을까요?',             exMeaning:'午饭吃什么？',          level:1},
  {id:48, korean:'저녁',    rom:'jeo-nyeok',       pos:'n',   meaning:'晚饭/傍晚',   example:'저녁에 같이 밥 먹어요.',         exMeaning:'晚上一起吃饭吧。',      level:1},
  {id:49, korean:'주말',    rom:'ju-mal',          pos:'n',   meaning:'周末',        example:'주말에 뭐 해요?',               exMeaning:'周末做什么？',          level:1},
  {id:50, korean:'주중',    rom:'ju-jung',         pos:'n',   meaning:'工作日',      example:'주중에는 일해요.',              exMeaning:'工作日在工作。',        level:1},
  {id:51, korean:'가다',    rom:'ga-da',           pos:'v',   meaning:'去',          example:'학교에 가요.',                  exMeaning:'去学校。',              level:1},
  {id:52, korean:'오다',    rom:'o-da',            pos:'v',   meaning:'来',          example:'빨리 와요!',                   exMeaning:'快来！',                level:1},
  {id:53, korean:'먹다',    rom:'meok-da',         pos:'v',   meaning:'吃',          example:'밥을 먹어요.',                  exMeaning:'吃饭。',                level:1},
  {id:54, korean:'마시다',  rom:'ma-si-da',        pos:'v',   meaning:'喝',          example:'물을 마셔요.',                  exMeaning:'喝水。',                level:1},
  {id:55, korean:'자다',    rom:'ja-da',           pos:'v',   meaning:'睡觉',        example:'일찍 자요.',                   exMeaning:'早点睡觉。',            level:1},
  {id:56, korean:'보다',    rom:'bo-da',           pos:'v',   meaning:'看',          example:'영화를 봐요.',                  exMeaning:'看电影。',              level:1},
  {id:57, korean:'듣다',    rom:'deut-da',         pos:'v',   meaning:'听',          example:'음악을 들어요.',               exMeaning:'听音乐。',              level:1},
  {id:58, korean:'말하다',  rom:'mal-ha-da',       pos:'v',   meaning:'说话',        example:'한국어로 말해요.',              exMeaning:'用韩语说话。',          level:1},
  {id:59, korean:'읽다',    rom:'ik-da',           pos:'v',   meaning:'读',          example:'책을 읽어요.',                  exMeaning:'读书。',                level:1},
  {id:60, korean:'쓰다',    rom:'sseu-da',         pos:'v',   meaning:'写/用',       example:'편지를 써요.',                  exMeaning:'写信。',                level:1},
  {id:61, korean:'사다',    rom:'sa-da',           pos:'v',   meaning:'买',          example:'옷을 사러 가요.',               exMeaning:'去买衣服。',            level:1},
  {id:62, korean:'팔다',    rom:'pal-da',          pos:'v',   meaning:'卖',          example:'과일을 팔아요.',               exMeaning:'卖水果。',              level:1},
  {id:63, korean:'앉다',    rom:'an-da',           pos:'v',   meaning:'坐',          example:'여기 앉아도 돼요?',             exMeaning:'可以坐这里吗？',        level:1},
  {id:64, korean:'서다',    rom:'seo-da',          pos:'v',   meaning:'站',          example:'줄을 서세요.',                  exMeaning:'请排队。',              level:1},
  {id:65, korean:'열다',    rom:'yeol-da',         pos:'v',   meaning:'打开',        example:'창문을 열어요.',               exMeaning:'打开窗户。',            level:1},
  {id:66, korean:'닫다',    rom:'dat-da',          pos:'v',   meaning:'关闭',        example:'문을 닫아요.',                  exMeaning:'关门。',                level:1},
  {id:67, korean:'주다',    rom:'ju-da',           pos:'v',   meaning:'给',          example:'선물을 줘요.',                  exMeaning:'送礼物。',              level:1},
  {id:68, korean:'받다',    rom:'bat-da',          pos:'v',   meaning:'接受/收',     example:'선물을 받았어요.',              exMeaning:'收到了礼物。',          level:1},
  {id:69, korean:'만나다',  rom:'man-na-da',       pos:'v',   meaning:'见面',        example:'내일 만나요.',                  exMeaning:'明天见面吧。',          level:1},
  {id:70, korean:'알다',    rom:'al-da',           pos:'v',   meaning:'知道/认识',   example:'그 사람 알아요?',               exMeaning:'你认识那个人吗？',      level:1},
  {id:71, korean:'좋다',    rom:'jo-ta',           pos:'adj', meaning:'好/喜欢',     example:'한국어가 좋아요.',              exMeaning:'我喜欢韩语。',          level:1},
  {id:72, korean:'크다',    rom:'keu-da',          pos:'adj', meaning:'大',          example:'집이 커요.',                   exMeaning:'房子很大。',            level:1},
  {id:73, korean:'작다',    rom:'jak-da',          pos:'adj', meaning:'小',          example:'방이 작아요.',                  exMeaning:'房间很小。',            level:1},
  {id:74, korean:'많다',    rom:'man-ta',          pos:'adj', meaning:'多',          example:'사람이 많아요.',               exMeaning:'人很多。',              level:1},
  {id:75, korean:'없다',    rom:'eop-da',          pos:'adj', meaning:'没有',        example:'시간이 없어요.',               exMeaning:'没有时间。',            level:1},
  {id:76, korean:'있다',    rom:'it-da',           pos:'adj', meaning:'有/在',       example:'질문이 있어요.',               exMeaning:'我有问题。',            level:1},
  {id:77, korean:'예쁘다',  rom:'ye-ppeu-da',      pos:'adj', meaning:'漂亮',        example:'꽃이 예쁘네요.',               exMeaning:'花真漂亮。',            level:1},
  {id:78, korean:'맛있다',  rom:'ma-sit-da',       pos:'adj', meaning:'好吃',        example:'이 음식은 맛있어요.',            exMeaning:'这食物好吃。',          level:1},
  {id:79, korean:'빠르다',  rom:'ppa-reu-da',      pos:'adj', meaning:'快',          example:'지하철이 빨라요.',              exMeaning:'地铁很快。',            level:1},
  {id:80, korean:'느리다',  rom:'neu-ri-da',       pos:'adj', meaning:'慢',          example:'버스가 너무 느려요.',            exMeaning:'公交车太慢了。',        level:1},
  {id:81, korean:'덥다',    rom:'deop-da',         pos:'adj', meaning:'热',          example:'오늘 너무 더워요.',             exMeaning:'今天太热了。',          level:1},
  {id:82, korean:'춥다',    rom:'chup-da',         pos:'adj', meaning:'冷',          example:'겨울이라서 추워요.',            exMeaning:'因为是冬天所以很冷。',  level:1},
  {id:83, korean:'비싸다',  rom:'bi-ssa-da',       pos:'adj', meaning:'贵',          example:'이 가방은 너무 비싸요.',         exMeaning:'这个包太贵了。',        level:1},
  {id:84, korean:'싸다',    rom:'ssa-da',          pos:'adj', meaning:'便宜',        example:'이 식당은 싸고 맛있어요.',       exMeaning:'这家餐厅便宜又好吃。',  level:1},
  {id:85, korean:'천천히',  rom:'cheon-cheon-hi',  pos:'adv', meaning:'慢慢地',      example:'천천히 말해 주세요.',           exMeaning:'请慢慢说。',            level:1},
  {id:86, korean:'빨리',    rom:'ppal-li',         pos:'adv', meaning:'快点',        example:'빨리 와요!',                   exMeaning:'快来！',                level:1},
  {id:87, korean:'같이',    rom:'ga-chi',          pos:'adv', meaning:'一起',        example:'같이 공부해요.',               exMeaning:'一起学习吧。',          level:1},
  {id:88, korean:'혼자',    rom:'hon-ja',          pos:'adv', meaning:'独自/一个人', example:'혼자 여행해요.',               exMeaning:'一个人旅行。',          level:1},
  {id:89, korean:'항상',    rom:'hang-sang',       pos:'adv', meaning:'总是',        example:'항상 건강하세요.',              exMeaning:'请一直保持健康。',      level:1},
  {id:90, korean:'가끔',    rom:'ga-kkeum',        pos:'adv', meaning:'偶尔',        example:'가끔 영화를 봐요.',             exMeaning:'偶尔看电影。',          level:1},

  // ==================== TOPIK 2 ====================
  {id:91,  korean:'경험',   rom:'gyeong-heom',     pos:'n',   meaning:'经验/经历',   example:'좋은 경험이 됐어요.',            exMeaning:'成为了很好的经历。',    level:2},
  {id:92,  korean:'계획',   rom:'gye-hoek',        pos:'n',   meaning:'计划',        example:'이번 방학 계획이 있어요?',        exMeaning:'这次假期有计划吗？',    level:2},
  {id:93,  korean:'기분',   rom:'gi-bun',          pos:'n',   meaning:'心情/感觉',   example:'오늘 기분이 어때요?',            exMeaning:'今天心情怎么样？',      level:2},
  {id:94,  korean:'노력',   rom:'no-ryeok',        pos:'n',   meaning:'努力',        example:'노력하면 성공할 수 있어요.',      exMeaning:'努力就能成功。',        level:2},
  {id:95,  korean:'문화',   rom:'mun-hwa',         pos:'n',   meaning:'文化',        example:'한국 문화에 관심이 있어요.',      exMeaning:'对韩国文化很感兴趣。',  level:2},
  {id:96,  korean:'방법',   rom:'bang-beop',       pos:'n',   meaning:'方法',        example:'좋은 방법이 없을까요?',          exMeaning:'有没有好方法呢？',      level:2},
  {id:97,  korean:'생각',   rom:'saeng-gak',       pos:'n',   meaning:'想法/思考',   example:'어떻게 생각해요?',              exMeaning:'你怎么想？',            level:2},
  {id:98,  korean:'성격',   rom:'seong-gyeok',     pos:'n',   meaning:'性格',        example:'그 사람은 성격이 좋아요.',        exMeaning:'那个人性格很好。',      level:2},
  {id:99,  korean:'소식',   rom:'so-sik',          pos:'n',   meaning:'消息',        example:'좋은 소식이 있어요.',            exMeaning:'有好消息。',            level:2},
  {id:100, korean:'약속',   rom:'yak-sok',         pos:'n',   meaning:'约定/承诺',   example:'약속을 꼭 지켜야 해요.',         exMeaning:'一定要遵守约定。',      level:2},
  {id:101, korean:'여행',   rom:'yeo-haeng',       pos:'n',   meaning:'旅行',        example:'여름에 유럽 여행을 갔어요.',      exMeaning:'夏天去欧洲旅行了。',    level:2},
  {id:102, korean:'운동',   rom:'un-dong',         pos:'n',   meaning:'运动/锻炼',   example:'매일 아침 운동을 해요.',         exMeaning:'每天早上锻炼。',        level:2},
  {id:103, korean:'이야기', rom:'i-ya-gi',         pos:'n',   meaning:'故事/话',     example:'재미있는 이야기를 해줘요.',       exMeaning:'给我讲有趣的故事。',    level:2},
  {id:104, korean:'준비',   rom:'jun-bi',          pos:'n',   meaning:'准备',        example:'시험 준비를 잘 했어요?',         exMeaning:'考试准备好了吗？',      level:2},
  {id:105, korean:'취미',   rom:'chwi-mi',         pos:'n',   meaning:'爱好',        example:'취미가 뭐예요?',               exMeaning:'你的爱好是什么？',      level:2},
  {id:106, korean:'환경',   rom:'hwan-gyeong',     pos:'n',   meaning:'环境',        example:'환경 보호가 중요해요.',          exMeaning:'保护环境很重要。',      level:2},
  {id:107, korean:'회사',   rom:'hoe-sa',          pos:'n',   meaning:'公司',        example:'회사에 취직했어요.',            exMeaning:'进公司就职了。',        level:2},
  {id:108, korean:'기억',   rom:'gi-eok',          pos:'n',   meaning:'记忆',        example:'어릴 때 기억이 나요?',          exMeaning:'记得小时候的事吗？',    level:2},
  {id:109, korean:'건강',   rom:'geon-gang',       pos:'n',   meaning:'健康',        example:'건강이 제일 중요해요.',          exMeaning:'健康是最重要的。',      level:2},
  {id:110, korean:'교통',   rom:'gyo-tong',        pos:'n',   meaning:'交通',        example:'서울은 교통이 편리해요.',         exMeaning:'首尔交通很便利。',      level:2},
  {id:111, korean:'직업',   rom:'ji-geop',         pos:'n',   meaning:'职业/工作',   example:'직업이 뭐예요?',               exMeaning:'你的职业是什么？',      level:2},
  {id:112, korean:'월급',   rom:'wol-geup',        pos:'n',   meaning:'月薪',        example:'월급이 얼마예요?',              exMeaning:'月薪是多少？',          level:2},
  {id:113, korean:'결혼',   rom:'gyeol-hon',       pos:'n',   meaning:'结婚',        example:'결혼식에 초대받았어요.',         exMeaning:'收到了婚礼邀请。',      level:2},
  {id:114, korean:'날짜',   rom:'nal-jja',         pos:'n',   meaning:'日期',        example:'날짜를 확인해 주세요.',          exMeaning:'请确认一下日期。',      level:2},
  {id:115, korean:'계절',   rom:'gye-jeol',        pos:'n',   meaning:'季节',        example:'어느 계절을 좋아해요?',          exMeaning:'你喜欢哪个季节？',      level:2},
  {id:116, korean:'봄',     rom:'bom',             pos:'n',   meaning:'春天',        example:'봄에 꽃이 피어요.',             exMeaning:'春天开花。',            level:2},
  {id:117, korean:'여름',   rom:'yeo-reum',        pos:'n',   meaning:'夏天',        example:'여름에는 덥고 습해요.',          exMeaning:'夏天又热又湿。',        level:2},
  {id:118, korean:'가을',   rom:'ga-eul',          pos:'n',   meaning:'秋天',        example:'가을 단풍이 아름다워요.',         exMeaning:'秋天的红叶很美。',      level:2},
  {id:119, korean:'겨울',   rom:'gyeo-ul',         pos:'n',   meaning:'冬天',        example:'겨울에 눈이 와요.',             exMeaning:'冬天下雪。',            level:2},
  {id:120, korean:'음악',   rom:'eu-mak',          pos:'n',   meaning:'音乐',        example:'음악을 들으며 공부해요.',         exMeaning:'边听音乐边学习。',      level:2},
  {id:121, korean:'영화',   rom:'yeong-hwa',       pos:'n',   meaning:'电影',        example:'주말에 영화를 봐요.',            exMeaning:'周末看电影。',          level:2},
  {id:122, korean:'요리',   rom:'yo-ri',           pos:'n',   meaning:'烹饪/料理',   example:'요리를 배우고 싶어요.',          exMeaning:'我想学做料理。',        level:2},
  {id:123, korean:'독서',   rom:'dok-seo',         pos:'n',   meaning:'读书',        example:'독서는 좋은 취미예요.',          exMeaning:'读书是好的爱好。',      level:2},
  {id:124, korean:'사진',   rom:'sa-jin',          pos:'n',   meaning:'照片',        example:'사진을 찍어 주세요.',           exMeaning:'请帮我拍照。',          level:2},
  {id:125, korean:'인터넷', rom:'in-teo-net',      pos:'n',   meaning:'网络/互联网', example:'인터넷으로 정보를 찾아요.',       exMeaning:'通过网络查找信息。',    level:2},
  {id:126, korean:'생활',   rom:'saeng-hwal',      pos:'n',   meaning:'生活',        example:'도시 생활이 편리해요.',          exMeaning:'城市生活很方便。',      level:2},
  {id:127, korean:'습관',   rom:'seup-gwan',       pos:'n',   meaning:'习惯',        example:'좋은 습관을 만드세요.',          exMeaning:'养成好习惯吧。',        level:2},
  {id:128, korean:'주소',   rom:'ju-so',           pos:'n',   meaning:'地址',        example:'주소를 알려 주세요.',           exMeaning:'请告诉我地址。',        level:2},
  {id:129, korean:'가격',   rom:'ga-gyeok',        pos:'n',   meaning:'价格',        example:'가격이 얼마예요?',              exMeaning:'价格是多少？',          level:2},
  {id:130, korean:'선물',   rom:'seon-mul',        pos:'n',   meaning:'礼物',        example:'생일 선물을 샀어요.',            exMeaning:'买了生日礼物。',        level:2},
  {id:131, korean:'편지',   rom:'pyeon-ji',        pos:'n',   meaning:'信件',        example:'편지를 썼어요.',               exMeaning:'写了信。',              level:2},
  {id:132, korean:'이메일', rom:'i-me-il',         pos:'n',   meaning:'电子邮件',    example:'이메일을 보냈어요.',            exMeaning:'发了电子邮件。',        level:2},
  {id:133, korean:'소개',   rom:'so-gae',          pos:'n',   meaning:'介绍',        example:'자기 소개를 해 주세요.',         exMeaning:'请做一下自我介绍。',    level:2},
  {id:134, korean:'기타',   rom:'gi-ta',           pos:'n',   meaning:'吉他',        example:'기타를 배우고 있어요.',          exMeaning:'正在学吉他。',          level:2},
  {id:135, korean:'피아노', rom:'pi-a-no',         pos:'n',   meaning:'钢琴',        example:'피아노를 잘 쳐요.',             exMeaning:'钢琴弹得很好。',        level:2},
  {id:136, korean:'감사하다',rom:'gam-sa-ha-da',   pos:'v',   meaning:'感谢',        example:'도와줘서 감사해요.',            exMeaning:'谢谢你的帮助。',        level:2},
  {id:137, korean:'노래하다',rom:'no-rae-ha-da',   pos:'v',   meaning:'唱歌',        example:'노래를 잘 해요.',              exMeaning:'唱歌唱得很好。',        level:2},
  {id:138, korean:'연습하다',rom:'yeon-seup-ha-da',pos:'v',   meaning:'练习',        example:'매일 연습해야 해요.',           exMeaning:'每天都要练习。',        level:2},
  {id:139, korean:'설명하다',rom:'seol-myeong-ha-da',pos:'v', meaning:'说明/解释',   example:'다시 설명해 주세요.',           exMeaning:'请再解释一遍。',        level:2},
  {id:140, korean:'확인하다',rom:'hwa-gin-ha-da',  pos:'v',   meaning:'确认',        example:'예약을 확인했어요.',            exMeaning:'确认了预约。',          level:2},
  {id:141, korean:'바쁘다', rom:'ba-ppeu-da',      pos:'adj', meaning:'忙',          example:'요즘 너무 바빠요.',             exMeaning:'最近太忙了。',          level:2},
  {id:142, korean:'편하다', rom:'pyeon-ha-da',     pos:'adj', meaning:'方便/舒适',   example:'이 옷이 편해요.',               exMeaning:'这衣服很舒服。',        level:2},
  {id:143, korean:'힘들다', rom:'him-deul-da',     pos:'adj', meaning:'辛苦/难',     example:'일이 힘들어요.',               exMeaning:'工作很辛苦。',          level:2},
  {id:144, korean:'피곤하다',rom:'pi-gon-ha-da',   pos:'adj', meaning:'疲累',        example:'너무 피곤해요.',               exMeaning:'太累了。',              level:2},
  {id:145, korean:'심심하다',rom:'sim-sim-ha-da',  pos:'adj', meaning:'无聊',        example:'심심해서 영화를 봤어요.',        exMeaning:'因为无聊就看了电影。',  level:2},
  {id:146, korean:'재미있다',rom:'jae-mi-it-da',   pos:'adj', meaning:'有趣',        example:'한국어 공부가 재미있어요.',       exMeaning:'学韩语很有趣。',        level:2},
  {id:147, korean:'조용하다',rom:'jo-yong-ha-da',  pos:'adj', meaning:'安静',        example:'도서관이 조용해요.',            exMeaning:'图书馆很安静。',        level:2},
  {id:148, korean:'시끄럽다',rom:'si-kkeu-reop-da',pos:'adj', meaning:'吵/嘈杂',     example:'공사 소리가 시끄러워요.',        exMeaning:'施工声音很吵。',        level:2},
  {id:149, korean:'자주',   rom:'ja-ju',           pos:'adv', meaning:'经常',        example:'자주 연락해요.',               exMeaning:'经常联系。',            level:2},
  {id:150, korean:'가끔씩', rom:'ga-kkeum-ssik',   pos:'adv', meaning:'偶尔/有时',   example:'가끔씩 고향에 가요.',            exMeaning:'偶尔回故乡。',          level:2},

  // ==================== TOPIK 3 ====================
  {id:151, korean:'가능성', rom:'ga-neung-seong',  pos:'n',   meaning:'可能性',      example:'성공할 가능성이 높아요.',         exMeaning:'成功的可能性很高。',    level:3},
  {id:152, korean:'관계',   rom:'gwan-gye',        pos:'n',   meaning:'关系',        example:'두 사람의 관계가 좋아요.',        exMeaning:'两个人关系很好。',      level:3},
  {id:153, korean:'결과',   rom:'gyeol-gwa',       pos:'n',   meaning:'结果',        example:'노력한 결과가 나타났어요.',        exMeaning:'努力的结果出现了。',    level:3},
  {id:154, korean:'목표',   rom:'mok-pyo',         pos:'n',   meaning:'目标',        example:'목표를 세우고 노력하세요.',        exMeaning:'设定目标后努力吧。',    level:3},
  {id:155, korean:'발전',   rom:'bal-jeon',        pos:'n',   meaning:'发展/进步',   example:'기술이 빠르게 발전하고 있어요.',  exMeaning:'技术正在快速发展。',    level:3},
  {id:156, korean:'사회',   rom:'sa-hoe',          pos:'n',   meaning:'社会',        example:'사회 문제를 해결해야 해요.',      exMeaning:'需要解决社会问题。',    level:3},
  {id:157, korean:'영향',   rom:'yeong-hyang',     pos:'n',   meaning:'影响',        example:'부모님의 영향을 많이 받았어요.',  exMeaning:'受了父母很大的影响。',  level:3},
  {id:158, korean:'원인',   rom:'won-in',          pos:'n',   meaning:'原因',        example:'실패의 원인을 분석했어요.',        exMeaning:'分析了失败的原因。',    level:3},
  {id:159, korean:'인기',   rom:'in-gi',           pos:'n',   meaning:'人气/受欢迎', example:'그 가수는 인기가 많아요.',        exMeaning:'那位歌手很受欢迎。',    level:3},
  {id:160, korean:'자신감', rom:'ja-sin-gam',      pos:'n',   meaning:'自信心',      example:'자신감을 가지고 도전하세요.',      exMeaning:'有自信地去挑战吧。',    level:3},
  {id:161, korean:'주의',   rom:'ju-ui',           pos:'n',   meaning:'注意',        example:'안전에 주의하세요.',            exMeaning:'请注意安全。',          level:3},
  {id:162, korean:'책임',   rom:'chaek-im',        pos:'n',   meaning:'责任',        example:'자기 행동에 책임을 져야 해요.',   exMeaning:'要为自己的行为负责。',  level:3},
  {id:163, korean:'태도',   rom:'tae-do',          pos:'n',   meaning:'态度',        example:'긍정적인 태도가 중요해요.',        exMeaning:'积极的态度很重要。',    level:3},
  {id:164, korean:'표현',   rom:'pyo-hyeon',       pos:'n',   meaning:'表达/表现',   example:'감정을 솔직하게 표현하세요.',      exMeaning:'坦率地表达感情吧。',    level:3},
  {id:165, korean:'현실',   rom:'hyeon-sil',       pos:'n',   meaning:'现实',        example:'현실을 직시해야 해요.',          exMeaning:'必须正视现实。',        level:3},
  {id:166, korean:'경쟁',   rom:'gyeong-jaeng',    pos:'n',   meaning:'竞争',        example:'경쟁이 너무 치열해요.',          exMeaning:'竞争太激烈了。',        level:3},
  {id:167, korean:'능력',   rom:'neung-nyeok',     pos:'n',   meaning:'能力',        example:'능력을 키워야 해요.',            exMeaning:'需要提高能力。',        level:3},
  {id:168, korean:'교육',   rom:'gyo-yuk',         pos:'n',   meaning:'教育',        example:'교육이 중요해요.',              exMeaning:'教育很重要。',          level:3},
  {id:169, korean:'정보',   rom:'jeong-bo',        pos:'n',   meaning:'信息',        example:'정보를 검색해요.',              exMeaning:'搜索信息。',            level:3},
  {id:170, korean:'기회',   rom:'gi-hoe',          pos:'n',   meaning:'机会',        example:'기회를 놓치지 마세요.',          exMeaning:'不要错过机会。',        level:3},
  {id:171, korean:'문제',   rom:'mun-je',          pos:'n',   meaning:'问题',        example:'문제가 생겼어요.',              exMeaning:'出现了问题。',          level:3},
  {id:172, korean:'해결',   rom:'hae-gyeol',       pos:'n',   meaning:'解决',        example:'문제를 해결했어요.',            exMeaning:'解决了问题。',          level:3},
  {id:173, korean:'과정',   rom:'gwa-jeong',       pos:'n',   meaning:'过程',        example:'결과보다 과정이 중요해요.',        exMeaning:'过程比结果更重要。',    level:3},
  {id:174, korean:'부족',   rom:'bu-jok',          pos:'n',   meaning:'不足/缺乏',   example:'경험이 부족해요.',              exMeaning:'经验不足。',            level:3},
  {id:175, korean:'이유',   rom:'i-yu',            pos:'n',   meaning:'理由/原因',   example:'이유를 말해 주세요.',           exMeaning:'请说出理由。',          level:3},
  {id:176, korean:'방향',   rom:'bang-hyang',      pos:'n',   meaning:'方向',        example:'방향을 잘못 잡았어요.',          exMeaning:'方向搞错了。',          level:3},
  {id:177, korean:'비교',   rom:'bi-gyo',          pos:'n',   meaning:'比较',        example:'두 가지를 비교해 봐요.',         exMeaning:'比较一下两个吧。',      level:3},
  {id:178, korean:'분위기', rom:'bun-wi-gi',       pos:'n',   meaning:'氛围/气氛',   example:'분위기가 좋아요.',              exMeaning:'气氛很好。',            level:3},
  {id:179, korean:'소통',   rom:'so-tong',         pos:'n',   meaning:'沟通/交流',   example:'원활한 소통이 필요해요.',         exMeaning:'需要顺畅的沟通。',      level:3},
  {id:180, korean:'성장',   rom:'seong-jang',      pos:'n',   meaning:'成长',        example:'경험을 통해 성장했어요.',         exMeaning:'通过经历成长了。',      level:3},
  {id:181, korean:'결정하다',rom:'gyeol-jeong-ha-da',pos:'v', meaning:'决定',        example:'스스로 결정하세요.',            exMeaning:'请自己决定。',          level:3},
  {id:182, korean:'포기하다',rom:'po-gi-ha-da',    pos:'v',   meaning:'放弃',        example:'절대 포기하지 마세요.',          exMeaning:'绝对不要放弃。',        level:3},
  {id:183, korean:'노력하다',rom:'no-ryeok-ha-da', pos:'v',   meaning:'努力',        example:'매일 노력하고 있어요.',          exMeaning:'每天都在努力。',        level:3},
  {id:184, korean:'발전하다',rom:'bal-jeon-ha-da', pos:'v',   meaning:'发展/进步',   example:'한국어 실력이 발전했어요.',        exMeaning:'韩语水平进步了。',      level:3},
  {id:185, korean:'이해하다',rom:'i-hae-ha-da',    pos:'v',   meaning:'理解',        example:'잘 이해했어요.',               exMeaning:'理解得很好。',          level:3},
  {id:186, korean:'중요하다',rom:'jung-yo-ha-da',  pos:'adj', meaning:'重要',        example:'건강이 가장 중요해요.',          exMeaning:'健康最重要。',          level:3},
  {id:187, korean:'복잡하다',rom:'bok-jap-ha-da',  pos:'adj', meaning:'复杂',        example:'이 문제는 복잡해요.',            exMeaning:'这个问题很复杂。',      level:3},
  {id:188, korean:'적극적', rom:'jeok-geuk-jeok',  pos:'adj', meaning:'积极',        example:'적극적인 자세로 임해요.',         exMeaning:'以积极的姿态去面对。',  level:3},
  {id:189, korean:'효과적', rom:'hyo-gwa-jeok',    pos:'adj', meaning:'有效',        example:'효과적인 방법을 찾아요.',         exMeaning:'寻找有效的方法。',      level:3},
  {id:190, korean:'결국',   rom:'gyeol-guk',       pos:'adv', meaning:'最终/结果',   example:'결국 성공했어요.',              exMeaning:'最终成功了。',          level:3},

  // ==================== TOPIK 4 ====================
  {id:191, korean:'갈등',   rom:'gal-deung',       pos:'n',   meaning:'矛盾/冲突',   example:'세대 간의 갈등이 심해졌어요.',    exMeaning:'代际矛盾加深了。',      level:4},
  {id:192, korean:'개선',   rom:'gae-seon',        pos:'n',   meaning:'改善/改进',   example:'제도의 개선이 필요해요.',         exMeaning:'需要改善制度。',        level:4},
  {id:193, korean:'논리',   rom:'nol-li',          pos:'n',   meaning:'逻辑',        example:'논리적으로 설명해 주세요.',        exMeaning:'请逻辑性地说明。',      level:4},
  {id:194, korean:'다양성', rom:'da-yang-seong',   pos:'n',   meaning:'多样性',      example:'문화의 다양성을 인정해야 해요.',  exMeaning:'应该承认文化多样性。',  level:4},
  {id:195, korean:'비판',   rom:'bi-pan',          pos:'n',   meaning:'批判/批评',   example:'건설적인 비판은 도움이 돼요.',    exMeaning:'建设性批评是有帮助的。',level:4},
  {id:196, korean:'상상력', rom:'sang-sang-nyeok', pos:'n',   meaning:'想象力',      example:'아이들의 상상력은 무한해요.',      exMeaning:'孩子们的想象力无限。',  level:4},
  {id:197, korean:'선택',   rom:'seon-taek',       pos:'n',   meaning:'选择',        example:'신중하게 선택해야 해요.',         exMeaning:'要慎重地选择。',        level:4},
  {id:198, korean:'의무',   rom:'ui-mu',           pos:'n',   meaning:'义务',        example:'납세는 국민의 의무예요.',         exMeaning:'纳税是国民的义务。',    level:4},
  {id:199, korean:'인식',   rom:'in-sik',          pos:'n',   meaning:'认识/意识',   example:'환경 문제에 대한 인식이 높아졌어요.',exMeaning:'对环境问题的意识提高了。',level:4},
  {id:200, korean:'전통',   rom:'jeon-tong',       pos:'n',   meaning:'传统',        example:'전통을 계승해야 해요.',          exMeaning:'应该继承传统。',        level:4},
  {id:201, korean:'창의성', rom:'chang-ui-seong',  pos:'n',   meaning:'创造性',      example:'창의성이 미래 인재의 핵심이에요.',exMeaning:'创造性是未来人才核心。',level:4},
  {id:202, korean:'평등',   rom:'pyeong-deung',    pos:'n',   meaning:'平等',        example:'모든 사람은 평등해요.',          exMeaning:'所有人都是平等的。',    level:4},
  {id:203, korean:'가치',   rom:'ga-chi',          pos:'n',   meaning:'价值',        example:'가치 있는 삶을 살아요.',         exMeaning:'过有价值的生活。',      level:4},
  {id:204, korean:'과학',   rom:'gwa-hak',         pos:'n',   meaning:'科学',        example:'과학 기술이 발전했어요.',         exMeaning:'科学技术发展了。',      level:4},
  {id:205, korean:'경제',   rom:'gyeong-je',       pos:'n',   meaning:'经济',        example:'경제가 어려워요.',              exMeaning:'经济很困难。',          level:4},
  {id:206, korean:'정치',   rom:'jeong-chi',       pos:'n',   meaning:'政治',        example:'정치에 관심이 있어요.',          exMeaning:'对政治很感兴趣。',      level:4},
  {id:207, korean:'복지',   rom:'bok-ji',          pos:'n',   meaning:'福祉/福利',   example:'사회 복지가 중요해요.',          exMeaning:'社会福利很重要。',      level:4},
  {id:208, korean:'협력',   rom:'hyeop-nyeok',     pos:'n',   meaning:'协作/合作',   example:'협력해서 일해요.',              exMeaning:'合作完成工作。',        level:4},
  {id:209, korean:'신뢰',   rom:'sil-loe',         pos:'n',   meaning:'信赖/信任',   example:'신뢰를 쌓는 것이 중요해요.',      exMeaning:'积累信任很重要。',      level:4},
  {id:210, korean:'전략',   rom:'jeol-lyak',       pos:'n',   meaning:'战略/策略',   example:'새로운 전략이 필요해요.',         exMeaning:'需要新的战略。',        level:4},
  {id:211, korean:'관점',   rom:'gwan-jeom',       pos:'n',   meaning:'观点',        example:'다양한 관점에서 생각해요.',        exMeaning:'从多种观点思考。',      level:4},
  {id:212, korean:'논의',   rom:'no-nui',          pos:'n',   meaning:'讨论/议论',   example:'이 문제를 논의해야 해요.',        exMeaning:'需要讨论这个问题。',    level:4},
  {id:213, korean:'주장',   rom:'ju-jang',         pos:'n',   meaning:'主张/主张',   example:'자신의 주장을 논리적으로 말해요.',exMeaning:'逻辑性地表达自己的主张。',level:4},
  {id:214, korean:'근거',   rom:'geun-geo',        pos:'n',   meaning:'根据/依据',   example:'근거를 제시해 주세요.',          exMeaning:'请提出依据。',          level:4},
  {id:215, korean:'비교하다',rom:'bi-gyo-ha-da',   pos:'v',   meaning:'比较',        example:'두 제품을 비교해 봤어요.',        exMeaning:'比较了两种产品。',      level:4},
  {id:216, korean:'분석하다',rom:'bun-seok-ha-da', pos:'v',   meaning:'分析',        example:'데이터를 분석했어요.',          exMeaning:'分析了数据。',          level:4},
  {id:217, korean:'강조하다',rom:'gang-jo-ha-da',  pos:'v',   meaning:'强调',        example:'중요성을 강조했어요.',          exMeaning:'强调了重要性。',        level:4},
  {id:218, korean:'논리적', rom:'nol-li-jeok',     pos:'adj', meaning:'逻辑性的',    example:'논리적으로 생각해요.',          exMeaning:'逻辑性地思考。',        level:4},
  {id:219, korean:'창의적', rom:'chang-ui-jeok',   pos:'adj', meaning:'创造性的',    example:'창의적인 아이디어가 필요해요.',   exMeaning:'需要有创意的想法。',    level:4},
  {id:220, korean:'합리적', rom:'ham-ni-jeok',     pos:'adj', meaning:'合理的',      example:'합리적인 결정을 했어요.',         exMeaning:'做出了合理的决定。',    level:4},
  {id:221, korean:'따라서', rom:'tta-ra-seo',      pos:'adv', meaning:'因此/所以',   example:'따라서 새로운 방법이 필요해요.',  exMeaning:'因此需要新的方法。',    level:4},
  {id:222, korean:'반면에', rom:'ban-myeon-e',     pos:'adv', meaning:'另一方面',    example:'장점도 있지만 반면에 단점도 있어요.',exMeaning:'有优点但另一方面也有缺点。',level:4},

  // ==================== TOPIK 5 ====================
  {id:223, korean:'구체적', rom:'gu-che-jeok',     pos:'adj', meaning:'具体的',      example:'구체적인 계획을 세워야 해요.',    exMeaning:'需要制定具体的计划。',  level:5},
  {id:224, korean:'논쟁',   rom:'non-jaeng',       pos:'n',   meaning:'争论/辩论',   example:'이 문제는 아직도 논쟁 중이에요.',exMeaning:'这个问题还在争论中。',  level:5},
  {id:225, korean:'도전',   rom:'do-jeon',         pos:'n',   meaning:'挑战',        example:'새로운 도전을 두려워하지 마세요.',exMeaning:'不要害怕新的挑战。',    level:5},
  {id:226, korean:'본질',   rom:'bon-jil',         pos:'n',   meaning:'本质',        example:'문제의 본질을 파악해야 해요.',    exMeaning:'需要掌握问题的本质。',  level:5},
  {id:227, korean:'역할',   rom:'yeok-hal',        pos:'n',   meaning:'角色/作用',   example:'리더의 역할이 매우 중요해요.',    exMeaning:'领导者的作用非常重要。',level:5},
  {id:228, korean:'우선순위',rom:'u-seon-sun-wi',  pos:'n',   meaning:'优先顺序',    example:'우선순위를 정해서 일해야 해요.',  exMeaning:'要确定优先顺序后工作。',level:5},
  {id:229, korean:'정체성', rom:'jeong-che-seong', pos:'n',   meaning:'身份认同',    example:'자신의 정체성을 잃지 마세요.',    exMeaning:'不要失去自己的身份认同。',level:5},
  {id:230, korean:'추론',   rom:'chu-ron',         pos:'n',   meaning:'推论/推断',   example:'증거를 바탕으로 추론했어요.',     exMeaning:'基于证据进行了推断。',  level:5},
  {id:231, korean:'패러다임',rom:'pae-reo-da-im',  pos:'n',   meaning:'范式/模式',   example:'새로운 패러다임이 필요한 시대예요.',exMeaning:'这是需要新范式的时代。',level:5},
  {id:232, korean:'모순',   rom:'mo-sun',          pos:'n',   meaning:'矛盾（逻辑）',example:'그의 말은 모순이 있어요.',       exMeaning:'他的话有矛盾。',        level:5},
  {id:233, korean:'맥락',   rom:'maeng-nak',       pos:'n',   meaning:'脉络/背景',   example:'맥락을 이해해야 해요.',          exMeaning:'需要理解背景脉络。',    level:5},
  {id:234, korean:'함의',   rom:'ham-ui',          pos:'n',   meaning:'含意/蕴意',   example:'이 발언의 함의가 뭔지 알아요?',  exMeaning:'你知道这句话的含意吗？',level:5},
  {id:235, korean:'전제',   rom:'jeon-je',         pos:'n',   meaning:'前提',        example:'이것을 전제로 이야기해요.',        exMeaning:'以此为前提来说。',      level:5},
  {id:236, korean:'추구하다',rom:'chu-gu-ha-da',   pos:'v',   meaning:'追求',        example:'행복을 추구해요.',              exMeaning:'追求幸福。',            level:5},
  {id:237, korean:'내포하다',rom:'nae-po-ha-da',   pos:'v',   meaning:'内含/包含',   example:'이 말은 여러 의미를 내포해요.',   exMeaning:'这句话包含多种含义。',  level:5},
  {id:238, korean:'수반하다',rom:'su-ban-ha-da',   pos:'v',   meaning:'伴随/包含',   example:'책임은 권리를 수반해요.',         exMeaning:'责任伴随着权利。',      level:5},

  // ==================== TOPIK 6 ====================
  {id:239, korean:'고찰',    rom:'go-chal',         pos:'n',  meaning:'考察/考量',   example:'철학적 고찰이 필요한 문제예요.',  exMeaning:'这是需要哲学性考察的问题。',level:6},
  {id:240, korean:'담론',    rom:'dam-non',         pos:'n',  meaning:'话语/论述',   example:'사회적 담론을 이끌어야 해요.',    exMeaning:'需要引领社会性话语。',    level:6},
  {id:241, korean:'메커니즘',rom:'me-keo-ni-jeum',  pos:'n',  meaning:'机制/机理',   example:'면역 메커니즘을 연구하고 있어요.',exMeaning:'正在研究免疫机制。',      level:6},
  {id:242, korean:'상호작용',rom:'sang-ho-jak-yong',pos:'n',  meaning:'相互作用',    example:'환경과 유전자의 상호작용이 중요해요.',exMeaning:'环境与基因相互作用很重要。',level:6},
  {id:243, korean:'역설',    rom:'yeok-seol',       pos:'n',  meaning:'悖论/逆说',   example:'자유의 역설에 대해 논의했어요.',  exMeaning:'讨论了自由的悖论。',      level:6},
  {id:244, korean:'이데올로기',rom:'i-de-ol-lo-gi', pos:'n',  meaning:'意识形态',    example:'이데올로기의 충돌이 역사를 바꿨어요.',exMeaning:'意识形态的冲突改变了历史。',level:6},
  {id:245, korean:'패권',    rom:'pae-gwon',        pos:'n',  meaning:'霸权',        example:'패권 경쟁이 심화되고 있어요.',    exMeaning:'霸权竞争正在加剧。',      level:6},
  {id:246, korean:'현상',    rom:'hyeon-sang',      pos:'n',  meaning:'现象',        example:'이 현상의 원인을 밝혀야 해요.',   exMeaning:'需要揭示这一现象的原因。', level:6},
  {id:247, korean:'변증법',  rom:'byeon-jeung-beop',pos:'n',  meaning:'辩证法',      example:'변증법적 사고방식이 필요해요.',   exMeaning:'需要辩证法式的思维方式。', level:6},
  {id:248, korean:'존재론',  rom:'jon-jae-ron',     pos:'n',  meaning:'本体论',      example:'존재론적 질문은 철학의 핵심이에요.',exMeaning:'本体论问题是哲学的核心。', level:6},

  // ==================== TOPIK 1 추가 ====================
  {id:301,korean:'어머니',  rom:'eo-meo-ni',       pos:'n',  meaning:'妈妈',        example:'어머니께서 밥을 해 주셨어요.',    exMeaning:'妈妈为我做了饭。',        level:1},
  {id:302,korean:'아버지',  rom:'a-beo-ji',        pos:'n',  meaning:'爸爸',        example:'아버지는 회사에 다니세요.',        exMeaning:'爸爸在公司上班。',        level:1},
  {id:303,korean:'형',      rom:'hyeong',          pos:'n',  meaning:'哥哥（男称）',example:'형이 저를 도와줬어요.',           exMeaning:'哥哥帮了我。',            level:1},
  {id:304,korean:'언니',    rom:'eon-ni',          pos:'n',  meaning:'姐姐（女称）',example:'언니 옷이 예뻐요.',              exMeaning:'姐姐的衣服很漂亮。',      level:1},
  {id:305,korean:'남동생',  rom:'nam-dong-saeng',  pos:'n',  meaning:'弟弟',        example:'남동생이 축구를 좋아해요.',        exMeaning:'弟弟喜欢足球。',          level:1},
  {id:306,korean:'여동생',  rom:'yeo-dong-saeng',  pos:'n',  meaning:'妹妹',        example:'여동생과 같이 공부해요.',          exMeaning:'和妹妹一起学习。',        level:1},
  {id:307,korean:'할머니',  rom:'hal-meo-ni',      pos:'n',  meaning:'奶奶/外婆',   example:'할머니 댁에 다녀왔어요.',          exMeaning:'去奶奶家回来了。',        level:1},
  {id:308,korean:'할아버지',rom:'ha-ra-beo-ji',    pos:'n',  meaning:'爷爷/外公',   example:'할아버지께 전화했어요.',           exMeaning:'给爷爷打了电话。',        level:1},
  {id:309,korean:'학생',    rom:'hak-saeng',       pos:'n',  meaning:'学生',        example:'저는 대학생이에요.',              exMeaning:'我是大学生。',            level:1},
  {id:310,korean:'선배',    rom:'seon-bae',        pos:'n',  meaning:'前辈/学长',   example:'선배한테 조언을 구했어요.',        exMeaning:'向前辈寻求了建议。',      level:1},
  {id:311,korean:'후배',    rom:'hu-bae',          pos:'n',  meaning:'后辈/学弟妹', example:'후배를 잘 챙겨야 해요.',           exMeaning:'要好好照顾后辈。',        level:1},
  {id:312,korean:'의사',    rom:'ui-sa',           pos:'n',  meaning:'医生',        example:'의사 선생님이 친절했어요.',        exMeaning:'医生很亲切。',            level:1},
  {id:313,korean:'간호사',  rom:'gan-ho-sa',       pos:'n',  meaning:'护士',        example:'간호사가 주사를 놔줬어요.',        exMeaning:'护士给打了针。',          level:1},
  {id:314,korean:'경찰',    rom:'gyeong-chal',     pos:'n',  meaning:'警察',        example:'경찰에게 신고했어요.',             exMeaning:'向警察报警了。',          level:1},
  {id:315,korean:'요리사',  rom:'yo-ri-sa',        pos:'n',  meaning:'厨师',        example:'요리사가 되고 싶어요.',            exMeaning:'我想成为厨师。',          level:1},
  {id:316,korean:'회사원',  rom:'hoe-sa-won',      pos:'n',  meaning:'公司职员',    example:'회사원이 되었어요.',              exMeaning:'成了公司职员。',          level:1},
  {id:317,korean:'음료수',  rom:'eum-nyo-su',      pos:'n',  meaning:'饮料',        example:'음료수를 한 캔 마셨어요.',         exMeaning:'喝了一罐饮料。',          level:1},
  {id:318,korean:'과일',    rom:'gwa-il',          pos:'n',  meaning:'水果',        example:'과일을 매일 먹어요.',              exMeaning:'每天吃水果。',            level:1},
  {id:319,korean:'야채',    rom:'ya-chae',         pos:'n',  meaning:'蔬菜',        example:'야채를 많이 먹어야 해요.',         exMeaning:'要多吃蔬菜。',            level:1},
  {id:320,korean:'고기',    rom:'go-gi',           pos:'n',  meaning:'肉',          example:'고기를 구워 먹었어요.',            exMeaning:'烤肉吃了。',              level:1},
  {id:321,korean:'생선',    rom:'saeng-seon',      pos:'n',  meaning:'鱼/海鲜',     example:'생선이 신선해요.',                exMeaning:'鱼很新鲜。',              level:1},
  {id:322,korean:'국',      rom:'guk',             pos:'n',  meaning:'汤',          example:'국이 맛있어요.',                  exMeaning:'汤很好喝。',              level:1},
  {id:323,korean:'김치',    rom:'gim-chi',         pos:'n',  meaning:'泡菜',        example:'한국 사람은 김치를 자주 먹어요.',  exMeaning:'韩国人经常吃泡菜。',      level:1},
  {id:324,korean:'냉면',    rom:'naeng-myeon',     pos:'n',  meaning:'冷面',        example:'여름에 냉면이 맛있어요.',          exMeaning:'夏天冷面很好吃。',        level:1},
  {id:325,korean:'비빔밥',  rom:'bi-bim-bap',      pos:'n',  meaning:'拌饭',        example:'비빔밥은 건강한 음식이에요.',      exMeaning:'拌饭是健康食品。',        level:1},
  {id:326,korean:'불고기',  rom:'bul-go-gi',       pos:'n',  meaning:'烤牛肉',      example:'불고기가 유명해요.',              exMeaning:'烤牛肉很有名。',          level:1},
  {id:327,korean:'찌개',    rom:'jji-gae',         pos:'n',  meaning:'锅/炖菜',     example:'김치찌개를 좋아해요.',             exMeaning:'喜欢泡菜锅。',            level:1},
  {id:328,korean:'눈',      rom:'nun',             pos:'n',  meaning:'雪/眼睛',     example:'눈이 많이 왔어요.',               exMeaning:'下了很多雪。',            level:1},
  {id:329,korean:'비',      rom:'bi',              pos:'n',  meaning:'雨',          example:'비가 오네요.',                    exMeaning:'下雨了呢。',              level:1},
  {id:330,korean:'바람',    rom:'ba-ram',          pos:'n',  meaning:'风',          example:'바람이 많이 불어요.',              exMeaning:'风很大。',                level:1},
  {id:331,korean:'구름',    rom:'gu-reum',         pos:'n',  meaning:'云',          example:'하늘에 구름이 가득해요.',          exMeaning:'天空中云很多。',          level:1},
  {id:332,korean:'해',      rom:'hae',             pos:'n',  meaning:'太阳',        example:'해가 뜨거워요.',                  exMeaning:'太阳很热。',              level:1},
  {id:333,korean:'달',      rom:'dal',             pos:'n',  meaning:'月亮',        example:'달이 밝아요.',                    exMeaning:'月亮很亮。',              level:1},
  {id:334,korean:'별',      rom:'byeol',           pos:'n',  meaning:'星星',        example:'별이 반짝여요.',                  exMeaning:'星星在闪烁。',            level:1},
  {id:335,korean:'강',      rom:'gang',            pos:'n',  meaning:'江/河',       example:'한강을 따라 걸었어요.',            exMeaning:'沿着汉江走了。',          level:1},
  {id:336,korean:'호수',    rom:'ho-su',           pos:'n',  meaning:'湖',          example:'호수 옆에 앉았어요.',              exMeaning:'坐在湖边。',              level:1},
  {id:337,korean:'숲',      rom:'sup',             pos:'n',  meaning:'森林',        example:'숲속을 산책했어요.',              exMeaning:'在森林里散步了。',        level:1},
  {id:338,korean:'도시',    rom:'do-si',           pos:'n',  meaning:'城市',        example:'도시 생활이 편리해요.',            exMeaning:'城市生活很方便。',        level:1},
  {id:339,korean:'시골',    rom:'si-gol',          pos:'n',  meaning:'农村/乡下',   example:'시골 공기가 맑아요.',              exMeaning:'乡下空气清新。',          level:1},
  {id:340,korean:'고향',    rom:'go-hyang',        pos:'n',  meaning:'故乡',        example:'고향이 그리워요.',                exMeaning:'思念故乡。',              level:1},
  {id:341,korean:'나이',    rom:'na-i',            pos:'n',  meaning:'年龄',        example:'나이가 어떻게 되세요?',            exMeaning:'请问您多大了？',          level:1},
  {id:342,korean:'키',      rom:'ki',              pos:'n',  meaning:'身高',        example:'키가 얼마예요?',                  exMeaning:'身高是多少？',            level:1},
  {id:343,korean:'몸무게',  rom:'mom-mu-ge',       pos:'n',  meaning:'体重',        example:'몸무게가 늘었어요.',              exMeaning:'体重增加了。',            level:1},
  {id:344,korean:'머리',    rom:'meo-ri',          pos:'n',  meaning:'头/头发',     example:'머리를 잘랐어요.',                exMeaning:'剪了头发。',              level:1},
  {id:345,korean:'눈',      rom:'nun',             pos:'n',  meaning:'眼睛',        example:'눈이 커요.',                      exMeaning:'眼睛很大。',              level:1},
  {id:346,korean:'코',      rom:'ko',              pos:'n',  meaning:'鼻子',        example:'코가 높아요.',                    exMeaning:'鼻子很高。',              level:1},
  {id:347,korean:'입',      rom:'ip',              pos:'n',  meaning:'嘴',          example:'입이 작아요.',                    exMeaning:'嘴很小。',                level:1},
  {id:348,korean:'손',      rom:'son',             pos:'n',  meaning:'手',          example:'손을 씻으세요.',                  exMeaning:'请洗手。',                level:1},
  {id:349,korean:'발',      rom:'bal',             pos:'n',  meaning:'脚',          example:'발이 아파요.',                    exMeaning:'脚疼。',                  level:1},
  {id:350,korean:'심장',    rom:'sim-jang',        pos:'n',  meaning:'心脏',        example:'심장이 빠르게 뛰어요.',            exMeaning:'心脏跳得很快。',          level:1},

  // ==================== TOPIK 2 추가 ====================
  {id:401,korean:'신청',    rom:'sin-cheong',      pos:'n',  meaning:'申请',        example:'강의를 신청했어요.',              exMeaning:'申请了讲座。',            level:2},
  {id:402,korean:'신청하다',rom:'sin-cheong-ha-da',pos:'v',  meaning:'申请',        example:'장학금을 신청했어요.',             exMeaning:'申请了奖学金。',          level:2},
  {id:403,korean:'참가하다',rom:'cham-ga-ha-da',   pos:'v',  meaning:'参加',        example:'대회에 참가했어요.',              exMeaning:'参加了比赛。',            level:2},
  {id:404,korean:'졸업하다',rom:'jo-reop-ha-da',   pos:'v',  meaning:'毕业',        example:'대학교를 졸업했어요.',             exMeaning:'大学毕业了。',            level:2},
  {id:405,korean:'입학하다',rom:'i-pak-ha-da',     pos:'v',  meaning:'入学',        example:'대학교에 입학했어요.',             exMeaning:'进入了大学。',            level:2},
  {id:406,korean:'이사하다',rom:'i-sa-ha-da',      pos:'v',  meaning:'搬家',        example:'새 집으로 이사했어요.',            exMeaning:'搬到新家了。',            level:2},
  {id:407,korean:'구경하다',rom:'gu-gyeong-ha-da', pos:'v',  meaning:'观看/游览',   example:'시장을 구경했어요.',              exMeaning:'逛了市场。',              level:2},
  {id:408,korean:'소개하다',rom:'so-gae-ha-da',    pos:'v',  meaning:'介绍',        example:'친구를 소개해 줬어요.',            exMeaning:'介绍了朋友。',            level:2},
  {id:409,korean:'교환하다',rom:'gyo-hwan-ha-da',  pos:'v',  meaning:'交换/换',     example:'전화번호를 교환했어요.',           exMeaning:'交换了电话号码。',        level:2},
  {id:410,korean:'비교하다',rom:'bi-gyo-ha-da',    pos:'v',  meaning:'比较',        example:'두 가격을 비교했어요.',            exMeaning:'比较了两个价格。',        level:2},
  {id:411,korean:'경험하다',rom:'gyeong-heom-ha-da',pos:'v', meaning:'经历/体验',   example:'새로운 것을 경험했어요.',          exMeaning:'体验了新事物。',          level:2},
  {id:412,korean:'시작하다',rom:'si-jak-ha-da',    pos:'v',  meaning:'开始',        example:'새 일을 시작했어요.',              exMeaning:'开始了新工作。',          level:2},
  {id:413,korean:'끝내다',  rom:'kkeun-nae-da',    pos:'v',  meaning:'结束/完成',   example:'일을 다 끝냈어요.',               exMeaning:'把工作都完成了。',        level:2},
  {id:414,korean:'포함하다',rom:'po-ham-ha-da',    pos:'v',  meaning:'包含',        example:'세금이 포함된 가격이에요.',        exMeaning:'是含税的价格。',          level:2},
  {id:415,korean:'이용하다',rom:'i-yong-ha-da',    pos:'v',  meaning:'使用/利用',   example:'대중교통을 이용해요.',             exMeaning:'利用公共交通。',          level:2},
  {id:416,korean:'기다리다',rom:'gi-da-ri-da',     pos:'v',  meaning:'等待',        example:'오래 기다렸어요.',                exMeaning:'等了很久。',              level:2},
  {id:417,korean:'떠나다',  rom:'tteo-na-da',      pos:'v',  meaning:'离开/出发',   example:'내일 서울을 떠나요.',              exMeaning:'明天离开首尔。',          level:2},
  {id:418,korean:'도착하다',rom:'do-chak-ha-da',   pos:'v',  meaning:'到达',        example:'약속 장소에 도착했어요.',          exMeaning:'到达了约定地点。',        level:2},
  {id:419,korean:'출발하다',rom:'chul-bal-ha-da',  pos:'v',  meaning:'出发',        example:'아침 일찍 출발했어요.',            exMeaning:'早上很早就出发了。',      level:2},
  {id:420,korean:'결정',    rom:'gyeol-jeong',     pos:'n',  meaning:'决定',        example:'중요한 결정을 내렸어요.',          exMeaning:'做出了重要决定。',        level:2},
  {id:421,korean:'연락',    rom:'yeol-lak',        pos:'n',  meaning:'联系',        example:'자주 연락해요.',                  exMeaning:'经常联系。',              level:2},
  {id:422,korean:'규칙',    rom:'gyu-chik',        pos:'n',  meaning:'规则',        example:'규칙을 지켜야 해요.',              exMeaning:'要遵守规则。',            level:2},
  {id:423,korean:'인상',    rom:'in-sang',         pos:'n',  meaning:'印象',        example:'첫인상이 중요해요.',              exMeaning:'第一印象很重要。',        level:2},
  {id:424,korean:'실수',    rom:'sil-su',          pos:'n',  meaning:'失误/错误',   example:'실수를 했어요. 죄송해요.',         exMeaning:'犯了错误，对不起。',      level:2},
  {id:425,korean:'결석',    rom:'gyeol-seok',      pos:'n',  meaning:'缺席',        example:'수업에 결석했어요.',              exMeaning:'缺课了。',                level:2},
  {id:426,korean:'출석',    rom:'chul-seok',       pos:'n',  meaning:'出席',        example:'출석을 불렀어요.',                exMeaning:'点名了。',                level:2},
  {id:427,korean:'용돈',    rom:'yong-don',        pos:'n',  meaning:'零花钱',      example:'용돈을 받았어요.',                exMeaning:'收到了零花钱。',          level:2},
  {id:428,korean:'할인',    rom:'ha-rin',          pos:'n',  meaning:'折扣',        example:'50% 할인 행사가 있어요.',          exMeaning:'有五折优惠活动。',        level:2},
  {id:429,korean:'영수증',  rom:'yeong-su-jeung',  pos:'n',  meaning:'收据',        example:'영수증을 주세요.',                exMeaning:'请给我收据。',            level:2},
  {id:430,korean:'예약',    rom:'ye-yak',          pos:'n',  meaning:'预约/预订',   example:'식당을 예약했어요.',              exMeaning:'预约了餐厅。',            level:2},
  {id:431,korean:'방문',    rom:'bang-mun',        pos:'n',  meaning:'访问/拜访',   example:'회사를 방문했어요.',              exMeaning:'拜访了公司。',            level:2},
  {id:432,korean:'대화',    rom:'dae-hwa',         pos:'n',  meaning:'对话/交谈',   example:'대화를 나눴어요.',                exMeaning:'进行了交谈。',            level:2},
  {id:433,korean:'편리하다',rom:'pyeol-li-ha-da',  pos:'adj',meaning:'便利',        example:'교통이 편리해요.',                exMeaning:'交通很便利。',            level:2},
  {id:434,korean:'불편하다',rom:'bul-pyeon-ha-da', pos:'adj',meaning:'不方便',      example:'의자가 불편해요.',                exMeaning:'椅子不舒服。',            level:2},
  {id:435,korean:'정확하다',rom:'jeong-hwak-ha-da',pos:'adj',meaning:'准确',        example:'정확한 정보가 필요해요.',          exMeaning:'需要准确的信息。',        level:2},
  {id:436,korean:'특별하다',rom:'teuk-byeol-ha-da',pos:'adj',meaning:'特别',        example:'오늘은 특별한 날이에요.',          exMeaning:'今天是特别的日子。',      level:2},
  {id:437,korean:'다르다',  rom:'da-reu-da',       pos:'adj',meaning:'不同/有区别',  example:'두 사람은 성격이 달라요.',         exMeaning:'两个人性格不同。',        level:2},
  {id:438,korean:'같다',    rom:'gat-da',          pos:'adj',meaning:'相同/一样',   example:'우리 생각이 같아요.',              exMeaning:'我们的想法一样。',        level:2},
  {id:439,korean:'쉽다',    rom:'swip-da',         pos:'adj',meaning:'容易',        example:'이 문제는 쉬워요.',               exMeaning:'这道题很简单。',          level:2},
  {id:440,korean:'어렵다',  rom:'eo-ryeop-da',     pos:'adj',meaning:'难',          example:'한국어는 처음에 어려워요.',        exMeaning:'韩语一开始很难。',        level:2},
  {id:441,korean:'늦다',    rom:'neut-da',         pos:'adj',meaning:'晚/迟',       example:'버스가 늦었어요.',                exMeaning:'公交车晚了。',            level:2},
  {id:442,korean:'이르다',  rom:'i-reu-da',        pos:'adj',meaning:'早',          example:'아직 이른 시간이에요.',            exMeaning:'还是早的时间。',          level:2},
  {id:443,korean:'무겁다',  rom:'mu-geop-da',      pos:'adj',meaning:'重',          example:'짐이 너무 무거워요.',              exMeaning:'行李太重了。',            level:2},
  {id:444,korean:'가볍다',  rom:'ga-byeop-da',     pos:'adj',meaning:'轻',          example:'이 가방은 가벼워요.',              exMeaning:'这个包很轻。',            level:2},
  {id:445,korean:'넓다',    rom:'neol-da',         pos:'adj',meaning:'宽/广',       example:'방이 넓어요.',                    exMeaning:'房间很宽敞。',            level:2},
  {id:446,korean:'좁다',    rom:'jop-da',          pos:'adj',meaning:'窄/狭小',     example:'골목이 좁아요.',                  exMeaning:'小巷很窄。',              level:2},
  {id:447,korean:'밝다',    rom:'bak-da',          pos:'adj',meaning:'亮/明亮',     example:'방이 밝아요.',                    exMeaning:'房间很明亮。',            level:2},
  {id:448,korean:'어둡다',  rom:'eo-dup-da',       pos:'adj',meaning:'暗',          example:'밤에는 어두워요.',                exMeaning:'晚上很暗。',              level:2},
  {id:449,korean:'조심하다',rom:'jo-sim-ha-da',    pos:'v',  meaning:'小心/注意',   example:'차 조심하세요.',                  exMeaning:'注意来往车辆。',          level:2},
  {id:450,korean:'걱정하다',rom:'geok-jeong-ha-da',pos:'v',  meaning:'担心',        example:'너무 걱정하지 마세요.',            exMeaning:'不要太担心。',            level:2},

  // ==================== TOPIK 3 추가 ====================
  {id:501,korean:'발음',    rom:'ba-reum',         pos:'n',  meaning:'发音',        example:'발음 연습을 많이 해요.',           exMeaning:'多做发音练习。',          level:3},
  {id:502,korean:'문법',    rom:'mun-beop',        pos:'n',  meaning:'语法',        example:'문법이 복잡해요.',                exMeaning:'语法很复杂。',            level:3},
  {id:503,korean:'어휘',    rom:'eo-hwi',          pos:'n',  meaning:'词汇',        example:'어휘력을 키워야 해요.',            exMeaning:'需要提高词汇量。',        level:3},
  {id:504,korean:'번역',    rom:'beon-yeok',       pos:'n',  meaning:'翻译',        example:'번역이 어려워요.',                exMeaning:'翻译很难。',              level:3},
  {id:505,korean:'통역',    rom:'tong-yeok',       pos:'n',  meaning:'口译',        example:'통역사가 필요해요.',              exMeaning:'需要口译员。',            level:3},
  {id:506,korean:'실력',    rom:'sil-lyeok',       pos:'n',  meaning:'实力/水平',   example:'한국어 실력이 늘었어요.',          exMeaning:'韩语水平提高了。',        level:3},
  {id:507,korean:'경력',    rom:'gyeong-nyeok',    pos:'n',  meaning:'经历/资历',   example:'경력이 중요해요.',                exMeaning:'资历很重要。',            level:3},
  {id:508,korean:'지식',    rom:'ji-sik',          pos:'n',  meaning:'知识',        example:'전문 지식이 필요해요.',            exMeaning:'需要专业知识。',          level:3},
  {id:509,korean:'제도',    rom:'je-do',           pos:'n',  meaning:'制度',        example:'제도를 개선해야 해요.',            exMeaning:'需要改善制度。',          level:3},
  {id:510,korean:'규정',    rom:'gyu-jeong',       pos:'n',  meaning:'规定',        example:'규정을 따라야 해요.',              exMeaning:'要遵守规定。',            level:3},
  {id:511,korean:'원칙',    rom:'won-chik',        pos:'n',  meaning:'原则',        example:'원칙을 지켜야 해요.',              exMeaning:'要遵守原则。',            level:3},
  {id:512,korean:'기준',    rom:'gi-jun',          pos:'n',  meaning:'基准/标准',   example:'기준이 무엇인가요?',              exMeaning:'标准是什么？',            level:3},
  {id:513,korean:'단계',    rom:'dan-gye',         pos:'n',  meaning:'阶段',        example:'단계별로 진행해요.',              exMeaning:'按阶段进行。',            level:3},
  {id:514,korean:'조건',    rom:'jo-geon',         pos:'n',  meaning:'条件',        example:'조건이 맞지 않아요.',              exMeaning:'条件不符合。',            level:3},
  {id:515,korean:'상황',    rom:'sang-hwang',      pos:'n',  meaning:'状况/情况',   example:'상황이 복잡해요.',                exMeaning:'情况很复杂。',            level:3},
  {id:516,korean:'특징',    rom:'teuk-jing',       pos:'n',  meaning:'特征/特点',   example:'한국 음식의 특징이에요.',          exMeaning:'是韩国饮食的特点。',      level:3},
  {id:517,korean:'장점',    rom:'jang-jeom',       pos:'n',  meaning:'优点',        example:'이 방법의 장점이 있어요.',         exMeaning:'这个方法有优点。',        level:3},
  {id:518,korean:'단점',    rom:'dan-jeom',        pos:'n',  meaning:'缺点',        example:'단점도 고려해야 해요.',            exMeaning:'也要考虑缺点。',          level:3},
  {id:519,korean:'의견',    rom:'ui-gyeon',        pos:'n',  meaning:'意见',        example:'의견을 말해 주세요.',              exMeaning:'请说出意见。',            level:3},
  {id:520,korean:'반응',    rom:'ba-neung',        pos:'n',  meaning:'反应',        example:'반응이 좋아요.',                  exMeaning:'反应很好。',              level:3},
  {id:521,korean:'평가',    rom:'pyeong-ga',       pos:'n',  meaning:'评价',        example:'좋은 평가를 받았어요.',            exMeaning:'得到了好评。',            level:3},
  {id:522,korean:'성과',    rom:'seong-gwa',       pos:'n',  meaning:'成果',        example:'좋은 성과를 거뒀어요.',            exMeaning:'取得了好成果。',          level:3},
  {id:523,korean:'기여',    rom:'gi-yeo',          pos:'n',  meaning:'贡献',        example:'사회에 기여했어요.',              exMeaning:'为社会做出了贡献。',      level:3},
  {id:524,korean:'지원',    rom:'ji-won',          pos:'n',  meaning:'支援/申请',   example:'회사에 지원했어요.',              exMeaning:'申请了公司。',            level:3},
  {id:525,korean:'합격',    rom:'hap-gyeok',       pos:'n',  meaning:'合格/通过',   example:'시험에 합격했어요!',              exMeaning:'通过考试了！',            level:3},
  {id:526,korean:'불합격',  rom:'bul-hap-gyeok',   pos:'n',  meaning:'不合格/未通过',example:'아쉽게도 불합격했어요.',           exMeaning:'遗憾地没有通过。',        level:3},
  {id:527,korean:'성공',    rom:'seong-gong',      pos:'n',  meaning:'成功',        example:'노력 끝에 성공했어요.',            exMeaning:'努力之后成功了。',        level:3},
  {id:528,korean:'실패',    rom:'sil-pae',         pos:'n',  meaning:'失败',        example:'실패를 두려워하지 마세요.',        exMeaning:'不要害怕失败。',          level:3},
  {id:529,korean:'도움',    rom:'do-um',           pos:'n',  meaning:'帮助',        example:'큰 도움이 됐어요.',               exMeaning:'帮了大忙了。',            level:3},
  {id:530,korean:'어려움',  rom:'eo-ryeo-um',      pos:'n',  meaning:'困难',        example:'어려움을 극복했어요.',             exMeaning:'克服了困难。',            level:3},

  // ==================== TOPIK 4 추가 ====================
  {id:601,korean:'세대',    rom:'se-dae',          pos:'n',  meaning:'世代/代际',   example:'세대 차이가 있어요.',              exMeaning:'有代际差异。',            level:4},
  {id:602,korean:'젊은이',  rom:'jeol-meun-i',     pos:'n',  meaning:'年轻人',      example:'젊은이들의 아이디어가 필요해요.',  exMeaning:'需要年轻人的想法。',      level:4},
  {id:603,korean:'노인',    rom:'no-in',           pos:'n',  meaning:'老年人',      example:'노인을 공경해야 해요.',            exMeaning:'要尊敬老年人。',          level:4},
  {id:604,korean:'소비자',  rom:'so-bi-ja',        pos:'n',  meaning:'消费者',      example:'소비자 권리를 보호해야 해요.',     exMeaning:'要保护消费者权益。',      level:4},
  {id:605,korean:'생산자',  rom:'saeng-san-ja',    pos:'n',  meaning:'生产者',      example:'생산자와 소비자가 연결돼요.',      exMeaning:'生产者和消费者相连接。',  level:4},
  {id:606,korean:'수요',    rom:'su-yo',           pos:'n',  meaning:'需求',        example:'수요가 늘었어요.',                exMeaning:'需求增加了。',            level:4},
  {id:607,korean:'공급',    rom:'gong-geup',       pos:'n',  meaning:'供给',        example:'공급이 부족해요.',                exMeaning:'供给不足。',              level:4},
  {id:608,korean:'투자',    rom:'tu-ja',           pos:'n',  meaning:'投资',        example:'미래에 투자해요.',                exMeaning:'向未来投资。',            level:4},
  {id:609,korean:'수익',    rom:'su-ik',           pos:'n',  meaning:'收益/利润',   example:'수익이 증가했어요.',              exMeaning:'收益增加了。',            level:4},
  {id:610,korean:'손실',    rom:'son-sil',         pos:'n',  meaning:'损失',        example:'손실을 최소화해야 해요.',          exMeaning:'要将损失最小化。',        level:4},
  {id:611,korean:'예산',    rom:'ye-san',          pos:'n',  meaning:'预算',        example:'예산 내에서 해결했어요.',          exMeaning:'在预算内解决了。',        level:4},
  {id:612,korean:'혁신',    rom:'hyeok-sin',       pos:'n',  meaning:'革新/创新',   example:'혁신적인 아이디어가 필요해요.',    exMeaning:'需要创新性想法。',        level:4},
  {id:613,korean:'효율',    rom:'hyo-yul',         pos:'n',  meaning:'效率',        example:'효율을 높여야 해요.',              exMeaning:'需要提高效率。',          level:4},
  {id:614,korean:'품질',    rom:'pum-jil',         pos:'n',  meaning:'品质/质量',   example:'품질 관리가 중요해요.',            exMeaning:'品质管理很重要。',        level:4},
  {id:615,korean:'서비스',  rom:'seo-bi-seu',      pos:'n',  meaning:'服务',        example:'서비스가 좋아요.',                exMeaning:'服务很好。',              level:4},
  {id:616,korean:'고객',    rom:'go-gaek',         pos:'n',  meaning:'顾客',        example:'고객 만족이 최우선이에요.',        exMeaning:'顾客满意是最优先的。',    level:4},
  {id:617,korean:'브랜드',  rom:'beu-raen-deu',    pos:'n',  meaning:'品牌',        example:'브랜드 이미지가 중요해요.',        exMeaning:'品牌形象很重要。',        level:4},
  {id:618,korean:'시장',    rom:'si-jang',         pos:'n',  meaning:'市场（经济）',example:'시장 경쟁이 치열해요.',            exMeaning:'市场竞争激烈。',          level:4},
  {id:619,korean:'인재',    rom:'in-jae',          pos:'n',  meaning:'人才',        example:'인재를 육성해야 해요.',            exMeaning:'需要培育人才。',          level:4},
  {id:620,korean:'조직',    rom:'jo-jik',          pos:'n',  meaning:'组织',        example:'조직 문화가 중요해요.',            exMeaning:'组织文化很重要。',        level:4},
  {id:621,korean:'성취',    rom:'seong-chwi',      pos:'n',  meaning:'成就/成就感',  example:'성취감을 느꼈어요.',              exMeaning:'感受到了成就感。',        level:4},
  {id:622,korean:'동기',    rom:'dong-gi',         pos:'n',  meaning:'动机',        example:'학습 동기가 중요해요.',            exMeaning:'学习动机很重要。',        level:4},
  {id:623,korean:'열정',    rom:'yeol-jeong',      pos:'n',  meaning:'热情',        example:'열정을 가지고 일해요.',            exMeaning:'带着热情工作。',          level:4},
  {id:624,korean:'의지',    rom:'ui-ji',           pos:'n',  meaning:'意志/意愿',   example:'강한 의지가 필요해요.',            exMeaning:'需要强大的意志。',        level:4},
  {id:625,korean:'포용',    rom:'po-yong',         pos:'n',  meaning:'包容',        example:'포용력이 있어야 해요.',            exMeaning:'要有包容力。',            level:4},
  {id:626,korean:'존중',    rom:'jon-jung',        pos:'n',  meaning:'尊重',        example:'서로 존중해야 해요.',              exMeaning:'要互相尊重。',            level:4},
  {id:627,korean:'배려',    rom:'bae-ryeo',        pos:'n',  meaning:'体贴/关怀',   example:'상대방을 배려해야 해요.',          exMeaning:'要体贴对方。',            level:4},
  {id:628,korean:'양보',    rom:'yang-bo',         pos:'n',  meaning:'让步/谦让',   example:'때로는 양보가 필요해요.',          exMeaning:'有时候需要让步。',        level:4},
  {id:629,korean:'타협',    rom:'ta-hyeop',        pos:'n',  meaning:'妥协/折衷',   example:'타협점을 찾아야 해요.',            exMeaning:'需要找到折中点。',        level:4},
  {id:630,korean:'공정',    rom:'gong-jeong',      pos:'n',  meaning:'公正',        example:'공정한 판단이 필요해요.',          exMeaning:'需要公正的判断。',        level:4},

  // ==================== TOPIK 5 추가 ====================
  {id:701,korean:'내재하다',rom:'nae-jae-ha-da',   pos:'v',  meaning:'内在/固有',   example:'문제가 내재해 있어요.',            exMeaning:'问题内在于此。',          level:5},
  {id:702,korean:'상충하다',rom:'sang-chung-ha-da',pos:'v',  meaning:'相冲/矛盾',   example:'두 가치가 상충해요.',              exMeaning:'两种价值相冲突。',        level:5},
  {id:703,korean:'귀결되다',rom:'gwi-gyeol-doe-da',pos:'v',  meaning:'归结/归纳',   example:'결국 하나로 귀결돼요.',            exMeaning:'最终归结为一个。',        level:5},
  {id:704,korean:'수렴하다',rom:'su-ryeom-ha-da',  pos:'v',  meaning:'收敛/汇聚',   example:'의견이 한 방향으로 수렴됐어요.',   exMeaning:'意见汇聚到一个方向。',    level:5},
  {id:705,korean:'파생하다',rom:'pa-saeng-ha-da',  pos:'v',  meaning:'派生/衍生',   example:'여러 문제가 파생됐어요.',          exMeaning:'衍生出了多个问题。',      level:5},
  {id:706,korean:'내포',    rom:'nae-po',          pos:'n',  meaning:'内涵/内包',   example:'깊은 내포를 가진 표현이에요.',     exMeaning:'是有深刻内涵的表达。',    level:5},
  {id:707,korean:'외연',    rom:'oe-yeon',         pos:'n',  meaning:'外延',        example:'개념의 외연을 넓혀야 해요.',       exMeaning:'需要扩大概念的外延。',    level:5},
  {id:708,korean:'패턴',    rom:'pae-teon',        pos:'n',  meaning:'模式/规律',   example:'패턴을 파악해야 해요.',            exMeaning:'需要掌握模式。',          level:5},
  {id:709,korean:'변수',    rom:'byeon-su',        pos:'n',  meaning:'变数/变量',   example:'여러 변수를 고려해야 해요.',       exMeaning:'需要考虑多种变数。',      level:5},
  {id:710,korean:'매개변수',rom:'mae-gae-byeon-su',pos:'n',  meaning:'参数/媒介',   example:'매개변수를 조정했어요.',           exMeaning:'调整了参数。',            level:5},
  {id:711,korean:'함수',    rom:'ham-su',          pos:'n',  meaning:'函数',        example:'이 함수의 의미를 분석해요.',       exMeaning:'分析这个函数的意义。',    level:5},
  {id:712,korean:'탐구',    rom:'tam-gu',          pos:'n',  meaning:'探究',        example:'진리를 탐구해요.',                exMeaning:'探究真理。',              level:5},
  {id:713,korean:'성찰',    rom:'seong-chal',      pos:'n',  meaning:'省察/反省',   example:'자기 성찰이 필요해요.',            exMeaning:'需要自我反省。',          level:5},
  {id:714,korean:'직관',    rom:'jik-gwan',        pos:'n',  meaning:'直觉',        example:'직관적으로 알 수 있어요.',         exMeaning:'可以直觉性地感知。',      level:5},
  {id:715,korean:'통찰',    rom:'tong-chal',       pos:'n',  meaning:'洞察/洞见',   example:'깊은 통찰이 있어요.',              exMeaning:'有深刻的洞察。',          level:5},
  {id:716,korean:'사유',    rom:'sa-yu',           pos:'n',  meaning:'思维/思考',   example:'깊은 사유가 필요해요.',            exMeaning:'需要深刻的思考。',        level:5},
  {id:717,korean:'개념',    rom:'gae-nyeom',       pos:'n',  meaning:'概念',        example:'개념을 정확히 이해해야 해요.',     exMeaning:'需要正确理解概念。',      level:5},
  {id:718,korean:'이론',    rom:'i-ron',           pos:'n',  meaning:'理论',        example:'이론과 실제가 달라요.',            exMeaning:'理论和实际不同。',        level:5},
  {id:719,korean:'법칙',    rom:'beop-chik',       pos:'n',  meaning:'法则',        example:'자연의 법칙을 따라요.',            exMeaning:'遵循自然法则。',          level:5},
  {id:720,korean:'원리',    rom:'won-ni',          pos:'n',  meaning:'原理',        example:'작동 원리를 이해했어요.',          exMeaning:'理解了工作原理。',        level:5},
  {id:721,korean:'가설',    rom:'ga-seol',         pos:'n',  meaning:'假说/假设',   example:'가설을 세웠어요.',                exMeaning:'提出了假设。',            level:5},
  {id:722,korean:'검증',    rom:'geom-jeung',      pos:'n',  meaning:'验证',        example:'가설을 검증해야 해요.',            exMeaning:'需要验证假设。',          level:5},
  {id:723,korean:'반증',    rom:'ban-jeung',       pos:'n',  meaning:'反证',        example:'반증 사례를 찾았어요.',            exMeaning:'找到了反证案例。',        level:5},
  {id:724,korean:'연역',    rom:'yeon-yeok',       pos:'n',  meaning:'演绎',        example:'연역적 방법으로 결론을 냈어요.',   exMeaning:'用演绎法得出了结论。',    level:5},
  {id:725,korean:'귀납',    rom:'gwi-nap',         pos:'n',  meaning:'归纳',        example:'귀납적 방식으로 접근했어요.',      exMeaning:'用归纳方式进行了分析。',  level:5},
  {id:726,korean:'상관관계',rom:'sang-gwan-gwan-gye',pos:'n',meaning:'相关关系',    example:'두 변수의 상관관계를 분석했어요.', exMeaning:'分析了两个变量的相关关系。',level:5},
  {id:727,korean:'인과관계',rom:'in-gwa-gwan-gye', pos:'n',  meaning:'因果关系',    example:'인과관계를 밝혀야 해요.',          exMeaning:'需要阐明因果关系。',      level:5},

  // ==================== TOPIK 6 추가 ====================
  {id:801,korean:'존재양식',rom:'jon-jae-yang-sik', pos:'n', meaning:'存在方式',    example:'인간의 존재양식을 탐구해요.',      exMeaning:'探究人类的存在方式。',    level:6},
  {id:802,korean:'세계관',  rom:'se-gye-gwan',     pos:'n',  meaning:'世界观',      example:'다양한 세계관이 있어요.',          exMeaning:'有多种世界观。',          level:6},
  {id:803,korean:'인생관',  rom:'in-saeng-gwan',   pos:'n',  meaning:'人生观',      example:'인생관을 정립해야 해요.',          exMeaning:'需要确立人生观。',        level:6},
  {id:804,korean:'가치관',  rom:'ga-chi-gwan',     pos:'n',  meaning:'价值观',      example:'가치관이 다를 수 있어요.',         exMeaning:'价值观可能不同。',        level:6},
  {id:805,korean:'초월',    rom:'cho-wol',         pos:'n',  meaning:'超越',        example:'한계를 초월하는 것이 목표예요.',   exMeaning:'超越界限是目标。',        level:6},
  {id:806,korean:'절대성',  rom:'jeol-dae-seong',  pos:'n',  meaning:'绝对性',      example:'절대성을 주장하기 어려워요.',      exMeaning:'很难主张绝对性。',        level:6},
  {id:807,korean:'상대성',  rom:'sang-dae-seong',  pos:'n',  meaning:'相对性',      example:'모든 것은 상대성이 있어요.',       exMeaning:'一切都有相对性。',        level:6},
  {id:808,korean:'진리',    rom:'jil-li',          pos:'n',  meaning:'真理',        example:'진리를 추구하는 삶을 살아요.',     exMeaning:'过着追求真理的生活。',    level:6},
  {id:809,korean:'허무주의',rom:'heo-mu-ju-ui',    pos:'n',  meaning:'虚无主义',    example:'허무주의를 극복해야 해요.',        exMeaning:'需要克服虚无主义。',      level:6},
  {id:810,korean:'실존주의',rom:'sil-jon-ju-ui',   pos:'n',  meaning:'存在主义',    example:'실존주의 철학을 공부했어요.',      exMeaning:'学习了存在主义哲学。',    level:6},
  {id:811,korean:'관념론',  rom:'gwan-nyeom-non',  pos:'n',  meaning:'观念论',      example:'관념론과 유물론을 비교했어요.',    exMeaning:'比较了观念论和唯物论。',  level:6},
  {id:812,korean:'유물론',  rom:'yu-mul-lon',      pos:'n',  meaning:'唯物论',      example:'마르크스는 유물론자였어요.',       exMeaning:'马克思是唯物论者。',      level:6},
  {id:813,korean:'변용',    rom:'byeon-yong',      pos:'n',  meaning:'变容/变形',   example:'시대에 따라 변용됐어요.',          exMeaning:'随时代发生了变容。',      level:6},
  {id:814,korean:'지양',    rom:'ji-yang',         pos:'n',  meaning:'扬弃/止扬',   example:'낡은 관념을 지양해야 해요.',       exMeaning:'需要扬弃旧观念。',        level:6},
  {id:815,korean:'지향',    rom:'ji-hyang',        pos:'n',  meaning:'指向/志向',   example:'올바른 방향을 지향해요.',          exMeaning:'指向正确的方向。',        level:6},
];

